---
- hosts: all
  sudo: yes
  tasks:
    - name: Update OS
      apt: upgrade=dist update_cache=yes
           dpkg_options='force-confold,force-confdef'
    - name: Install must-have packages
      apt: pkg={{ item }} state=latest
      with_items:
        - git
        - vim-nox
        - mc
        - tmux
