---
- hosts: all
  become: yes
  tasks:
  - name: Update operating system
    apt: upgrade=dist update_cache=yes
         dpkg_options='force-confold,force-confdef'
    notify:
      - Remove unneeded packages
      - Clean package cache
  - name: Install essential packages
    apt: pkg={{ item }} state=latest
    with_items:
      - git
      - vim-nox
      - mc
  handlers:
    - name: Remove unneeded packages
      shell: apt-get -y --force-yes autoremove
      args:
        warn: no
    - name: Clean package cache
      shell: apt-get clean
      args:
        warn: no

- include: ./ssh.yml
- include: ./tmux.yml
