---
- hosts: ispconfig
  become: yes
  vars:
    default_ttl: 86400
    correct_ttl: 300
    dns_form_path: "/usr/local/ispconfig/interface/web/dns/form"
    ttl_changed_flag: "{{ dns_form_path }}/.ttl_changed"
  tasks:
  - name: Change default DNS TTL
    shell: "find {{ dns_form_path }} -type f -name '*.php' | xargs sed -i 's/{{ default_ttl }}/{{ correct_ttl }}/g;' && touch {{ ttl_changed_flag }}"
    args:
      warn: no
      creates: "{{ ttl_changed_flag }}"
