---
- hosts: all
  become: yes
  vars:
    apt_repository: 'ppa:brightbox/ruby-ng'
    ruby_version: '2.2'
  tasks:
  - name: Add PPA for Ruby
    apt_repository: repo={{ apt_repository }} state=present update_cache=yes
  - name: Install Ruby
    apt: pkg={{ item }} state=latest
    with_items:
      - "ruby{{ ruby_version }}"
      - "ruby{{ ruby_version }}-dev"

