---
- hosts: all
  become: yes
  tasks:
  - name: Create tmux system-level config
    copy: src=../files/etc/tmux.conf
          dest=/etc/tmux.conf
          owner=root
          group=root
          mode=0644
  - name: Install tmux
    apt: pkg=tmux state=latest
